version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/src
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:8.1
    ports:
      - 3306:3306
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
volumes:
  db: